version: '3'

networks: 
    main:


services:

    zookeeper:
        image: zookeeper
        networks: 
            - main
        ports:
            - 2181:2181
    
    ch1:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        ports:
            - 8811:8123
            - 9011:9000
        expose:
            - "9011"
        networks: 
            - main
        volumes:
            - "./volume1:/var/lib/clickhouse"
  
    ch2:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        ports:
            - 8812:8123
            - 9012:9000
        expose:
            - "9012"
        networks: 
            - main
        volumes:
            - "./volume2:/var/lib/clickhouse"
  
    ch3:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        ports:
            - 8813:8123
            - 9013:9000
        networks: 
            - main
        expose:
            - "9013"
        volumes:
            - "./volume3:/var/lib/clickhouse"
  
    ch4:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        ports:
            - 8814:8123
            - 9014:9000
        networks: 
            - main
        expose:
            - "9014"
        volumes:
            - "./volume4:/var/lib/clickhouse"
