version: "3"

networks: 
    main:


services:

    zookeeper:
        image: zookeeper
        networks: 
            - main
        ports:
            - 2181:2181
    
    ch1:
        build:
            context: ./shard-1/instance-1/
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        networks: 
            - main
        volumes:
            - ./shard-1/instance-1/volume:/var/lib/clickhouse
            - ./shard-1/instance-1/log:/var/log/clickhouse-server
  
    ch2:
        build:
            context: ./shard-1/instance-2/
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        networks: 
            - main
        volumes:
            - ./shard-1/instance-2/volume:/var/lib/clickhouse
            - ./shard-1/instance-2/log:/var/log/clickhouse-server
  
    ch3:
        build:
            context: ./shard-2/instance-3/
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        networks: 
            - main
        volumes:
            - ./shard-2/instance-3/volume:/var/lib/clickhouse
            - ./shard-2/instance-3/log:/var/log/clickhouse-server
  
    ch4:
        build:
            context: ./shard-2/instance-4/
            dockerfile: Dockerfile
        depends_on:
            - zookeeper
        networks: 
            - main
        volumes:
            - ./shard-2/instance-4/volume:/var/lib/clickhouse
            - ./shard-2/instance-4/log:/var/log/clickhouse-server
